stages:
  - deploy

deploy-railway:
  stage: deploy
  image: ubuntu
  only:
    - pushes
    - gabriel_baru
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - echo $RAILWAY_TOKEN | railway login
    - railway up --service=$RAILWAY_SERVICE_NAME -d